--- 
jobs: 
  build: 
    docker: 
      - 
        image: "circleci/python:3.6.1"
    steps: 
      - checkout
      - 
        run: 
          command: "python --version"
          name: "python version"
      - 
        run: 
          command: "sudo apt install python-pip -y"
          name: "install pip"
      - 
        run: 
          command: "pip install --upgrade pip"
          name: machineinfo
      - 
        run: 
          command: "pip --version"
          name: "pip version"
      - 
        run: 
          command: "pip install Flask"
          name: "install flask"
      - 
        run: 
          command: "python app.py"
          name: machineinfo
    working_directory: ~/repo
version: 2
