version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.1

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command:
            apt install python-pip
            pip install -U Flask
            python app.py
