version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: python version
          command:
            python --version
      - run:
          name: install pip
          command:
            sudo apt install python-pip -y
      - run:
          name: pip version
          command:
            pip --version
      - run:
          name: install flask
          command:
            pip install Flask
      - run:
          name: machineinfo
          command:
            python app.py

